language: rust

os: linux
rust: stable
dist: trusty
env:
  global:
    - RUSTFLAGS="-C link-dead-code -C target-cpu=native"
cache:
  directories:
    - /home/travis/.cargo

before_cache:
  - cargo install cargo-tarpaulin
  - rm -rf /home/travis/.cargo/registry

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-8
    packages:
      - llvm-8-dev
      - libelf-dev
      - lib32z1-dev
      - libedit-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

before_install:
  - export PATH=/usr/lib/llvm-8.0/bin/:$HOME/.local/bin:$PATH

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi

notifications:
  email: false
