language: rust

sudo: false

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - llvm-3.7-dev
      - libelf-dev
      - lib32z1-dev
      - libedit-dev
      - libdw-dev

before_install:
  - export PATH=/usr/lib/llvm-3.7/bin/:$HOME/.local/bin:$PATH

# Get and load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# Build, test, bench, and build docs
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc

after_success:
  # Upload the docs
  - travis-cargo --only stable doc-upload

  # Upload the code coverage to coveralls
  - |
      sudo add-apt-repository -y ppa:kubuntu-ppa/backports &&
      sudo apt-get update &&
      sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev &&
      wget https://github.com/SimonKagstrom/kcov/archive/v33.tar.gz &&
      tar xzf v33.tar.gz && mkdir kcov-33/build && cd kcov-33/build && cmake .. && make &&
      sudo make install && cd ../.. &&
      kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov $(find target/debug -maxdepth 1 -executable -name limonite-\*)

notifications:
  email: false
