language: rust

os: linux
rust: stable
dist: bionic
env:
  global:
    - RUSTFLAGS="-C link-dead-code -C target-cpu=native"
cache:
  directories:
    - /home/travis/.cargo

before_cache:
  - cargo install cargo-tarpaulin
  - rm -rf /home/travis/.cargo/registry

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-bionic-10
      - sourceline: 'deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - llvm-10-dev
      - libclang-common-10-dev
      - libelf-dev
      - lib32z1-dev
      - libedit-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

before_install:
  - export PATH=/usr/lib/llvm-10/bin/:$HOME/.local/bin:$PATH

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi

notifications:
  email: false
